# Generated by Django 4.1 on 2022-10-11 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_coordinates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coordinates',
            new_name='LatLon',
        ),
    ]
