# Generated by Django 4.1 on 2022-10-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_coordinates_latlon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latlon',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='latlon',
            name='lon',
            field=models.FloatField(),
        ),
    ]
