# Generated by Django 4.1 on 2022-10-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_latlon_lat_alter_latlon_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latlon',
            name='lat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='latlon',
            name='lon',
            field=models.IntegerField(),
        ),
    ]
