# Generated by Django 4.1 on 2022-10-14 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_latlon_lat_alter_latlon_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='latlon',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Point_post', to='posts.post'),
        ),
    ]
