# Generated by Django 4.1 on 2022-10-14 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latlon',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='point',
        ),
    ]
