# Generated by Django 4.1 on 2022-10-14 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_remove_latlon_post_remove_post_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='latlon',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='posts.post'),
        ),
    ]
