# Generated by Django 4.1 on 2022-10-14 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_latlon_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latlon',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='Coor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='posts.latlon'),
        ),
    ]
