# Generated by Django 4.1 on 2022-10-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_latlon_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='latlon',
            name='destination',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
