# Generated by Django 4.1 on 2022-10-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_alter_latlon_lat_alter_latlon_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='latlon',
            name='lat',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='latlon',
            name='lon',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
