# Generated by Django 4.1 on 2022-11-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_alter_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Coor',
        ),
    ]
