# Generated by Django 4.1.3 on 2022-11-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_remove_post_coor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('date_of_birth', models.DateTimeField()),
                ('avatar', models.ImageField(blank=True, upload_to='media/avatars', verbose_name='Avatar')),
            ],
        ),
    ]
